export const stockDomande = [
  {
    id : "1",
    domanda : "Quali tra questi è un sistema operativo open source?",
    A : "Windows",
    B : "MacOS",
    C : "Ubuntu",
    D : "Nessuna delle precedenti",
    corretta : "C",
  },
  {
    id : "2",
    domanda : "In un servizio DNS quale tra questi protocollo viene usato assegnare un nome ad un indirizzo ip?",
    A : "CNAME",
    B : "A Record",
    C : "SOA",
    D : "NS Record",
    corretta : "B",
  },
  {
    id : "3",
    domanda : "Quale tra questi linguaggi di programmazione è compilato?",
    A : "C",
    B : "Python",
    C : "JavaScript",
    D : "PHP",
    corretta : "A",
  },
  {
    id : "4",
    domanda : "Quale tra questi non è una funzione sql per i database?",
    A : "DDL",
    B : "DML",
    C : "Query Language",
    D : "DFL",
    corretta : "D",
  },
  {
    id : "5",
    domanda : "Quali tra questi linguaggi di programmazione viene utilizzato per creare dei web services?",
    A : "React Native",
    B : "Nodejs",
    C : "HTML",
    D : "XML",
    corretta : "B",
  },
  {
    id : "6",
    domanda : "Quali tra queste non è una fase del processo di produzione di un software?",
    A : "Progetto",
    B : "Manutenzione",
    C : "Sviluppo",
    D : "Idealizzazione",
    corretta : "D",
  },
  {
    id : "7",
    domanda : "Quale tra questi è l’autore de “Il fanciullino”?",
    A : "Pascoli",
    B : "D’Annunzio",
    C : "Manzoni",
    D : "D’Avenia",
    corretta : "A",
  },
  {
    id : "8",
    domanda : "Chi erano i bolscevichi?",
    A : "Democratici",
    B : "Comunisti",
    C : "Nazisti",
    D : "Fascisti",
    corretta : "B",
  },
  {
    id : "9",
    domanda : "Quanto fa l’integrale di x^2 dx?",
    A : "2x^2",
    B : "2x",
    C : "(x^3)/3",
    D : "(x^2)/2",
    corretta : "C",
  },
  {
    id : "10",
    domanda : " Which one of these is not a basic function of a computer?",
    A : "Storing",
    B : "Processing",
    C : "Input",
    D : "Data reading",
    corretta : "D",
  },
];